sudo: false
language: node_js
addons:
  sauce_connect: true
cache:
  directories:
  - node_modules
node_js:
 - 6 # to be removed 2019-04-30
 - 8 # to be removed 2019-12-31
 - 10 # to be removed 2021-04-30
 - lts/* # safety net; don't remove
 - node # safety net; don't remove
before_install:
- npm i -g npm
script:
- npm t
after_success:
- npm run upload-coverage
- travis-after-all && npm run semantic-release
env:
  global:
  - SAUCE_CONNECT_READY_FILE=/tmp/sauce-connect-ready
  - LOGS_DIR=/tmp/chai-build/logs

    # SAUCE_USERNAME
  - secure: FNulH4KLpwQGttsxyu4jpjdclkKBgvUBO25ED1hcFvRESUxVjefTYpU6EhSTTNCTTF3wIRClhXjWAffvo4aG0VuOLqxvEiDYiJmcuR2I4oI6f+FgSIW2/4qmIb1GddvvNOxvFC9j2fV2TEDX2+SX1V93OjuVQxOdekO19ldK/Xo=
    # SAUCE_ACCESS_KEY
  - secure: fnfedefBCwAZi6pONa4ogEimc4rK/f3sd1gHIbv9evifdn8LkLEagR3LOInxmbdBIZ2a9NmIyeZAveVr5ox6xa3BFTqs5HxweOh7gl3ur38ySRftJWf/Lj/fNptDbm1eVUblXwCxbADlIQ3KdElhNN02G3giRVkSYHSz7XthI6A=
    # GH_TOKEN deep-eql travis 
  - secure: rljXmWTNLbjPZ+CDO1FQt20AX4ED4UKMrKXK3eLQj2ZuWi1jQdek6WYqnmPra2aR+NkLmRIru2tdyDqHfUSPGdNiPlf/yEQ0GADXdrfkohEmXJGyVdcQQIeyvKeLvVf+c5kLU3c5gstoZ9eE4VbT0ANUv5sxtg/bc3eJOwPbCNA=
    # NPM_TOKEN 54d3......c356
  - secure: FPBrJPIEDzQwNcRtaEil/3DRB/oZthfClJVIwnhUeIDG73sB2rK49+7lVdNa/qOMSgK2f0GQsquDgHWwsL6ezfyf5VgsrqGA/LhGR4mZdVDQt4Jjn+pynXH7XyVDbqPg/mIO5J+HKvZV1n8DVT4fgmhrNT+4+kSHKHMWY5Cl/X4=
